//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catEmpleado
    {
        public catEmpleado()
        {
            this.catHistorial = new HashSet<catHistorial>();
            this.catPermisos = new HashSet<catPermisos>();
        }
    
        public int noEmpleado { get; set; }
        public string nomEmpleado { get; set; }
        public string patEmpleado { get; set; }
        public string matEmpleado { get; set; }
        public Nullable<int> tipoEmpleado { get; set; }
        public string id { get; set; }
        public Nullable<int> noHorasAginadas { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual catCategorias catCategorias { get; set; }
        public virtual ICollection<catHistorial> catHistorial { get; set; }
        public virtual ICollection<catPermisos> catPermisos { get; set; }
    }
}
