//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFechasEspeciales
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<double> inicio { get; set; }
        public Nullable<double> fin { get; set; }
        public string clase { get; set; }
        public Nullable<bool> todoElDia { get; set; }
        public Nullable<int> tipo { get; set; }
        public Nullable<bool> ignorarHorario { get; set; }
    }
}
