//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class catHistorial
    {
        public int idHistorial { get; set; }
        public Nullable<int> noEmpleado { get; set; }
        public Nullable<System.DateTime> hraEntrada { get; set; }
        public Nullable<System.DateTime> hraSalida { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual catEmpleado catEmpleado { get; set; }
    }
}
